openapi: 3.1.0
info:
  title: Taxi Mobile Application API
  description: API for clients and drivers
  version: 1.0.0
servers:
  - url: https://taxi.example.com/api
    description: API server

paths:
/clientSms:
    post:
      summary: Verify client mobile number  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                moobile:
                  type: string
              required:
                - mobile
      responses:
        "200":
          description: Successful verification
        "401":
          description: Invalid credentials
/clientRegister:
    post:
      summary: Request for client registration  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userType:
                  type: string
                moobile:
                  type: string
              required:
                - mobile
                - userType
      responses:
        "200":
          description: Successful create lite account and send verify code in sms
        "400":
          description: Invalid credentials
/clientLogin:
  post:
    summary: Send verification code via SMS
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              smsCode:
                type: string
            required:
              - smsCode
    responses:
      "200":
        description: Successful verification
        content:
          application/json:
            schema:
              type: object
              properties:
                authToken:
                  type: string
                userType: 
                  type: string
                  enum: ['client', 'driver']
                moderated:
                  type: integer
                  enum: [0, 1]
                newAccount:
                  type: integer
                  enum: [0, 1]
                firstName:
                  type: string
                lastName:
                  type: string
                mobile:
                  type: string
                image:
                  type: string
                email:
                  type: string
                  format: email
                birth:
                  type: string
      "400":
        description: Invalid credentials
/clientProfile:
        summary: Get client detail 
        parameters:
       - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
          responses:
        "200":
          description: Get client profile info
          content:
            application/json:
              schema:
                type: object
                properties:
                id:
                  type: integer
                firstName:
                  type: string
                lastName:
                  type: string
                mobile:
                  type: string
                image:
                  type: string
                email:
                  type: string
                  format: email
                birth:
                  type: string
        "401":
          description: Unauthorized
/clientRrofileEdit:
  post:
    summary: Edition or add new profile data
    parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - name: id
          in: query  
          required: true
          schema:
            type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
            firstName:
              type: string
            lastName:
              type: string
            mobile:
              type: string
            image:
              type: string
            email:
              type: string
              format: email
            birth:
                type: string
            required:
              - mobile
              - firstName
              - lastName
    responses:
      "200":
        description: Successful profile edition
        content:
          application/json:
            schema:
              type: object
              properties:
                moderated:
                  type: integer
                  enum: [0, 1]
                newAccount:
                  type: integer
                  enum: [0, 1]
                id:
                 type: integer 
                firstName:
                  type: string
                lastName:
                  type: string
                mobile:
                  type: string
                image:
                  type: string
                email:
                  type: string
                  format: email
                birth:
                  type: string
      "400":
        description: Invalid credentials
      "401":
          description: Unauthorized
/driverProfile:
        summary: Get driver detail 
        parameters:
       - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
          responses:
        "200":
          description: Get driver profile info
          content:
            application/json:
              schema:
                type: object
                properties:
                id:
                  type: integer
                number:
                  type: string  
                firstName:
                  type: string
                lastName:
                  type: string
                mobile:
                  type: string
                image:
                  type: string
                email:
                  type: string
                  format: email
                birth:
                  type: string
                company:
                  type: string
        "401":
          description: Unauthorized
/driverRrofileEdit:
  post:
    summary: Edition or add new driver profile data
    parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - name: id
          in: query  
          required: true
          schema:
            type: integer    
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              number:
                  type: string  
              firstName:
                  type: string
              lastName:
                  type: string
              mobile:
                  type: string
              image:
                  type: string
              email:
                  type: string
                  format: email
              birth:
                  type: string
              company:
                  type: string
              required:    
              - number    
              - mobile
              - firstName
              - lastName
              - company
    responses:
      "200":
        description: Successful driver profile edition
        content:
          application/json:
            schema:
              type: object
              properties:
                moderated:
                  type: integer
                  enum: [0, 1]
                newAccount: 
                  type: integer
                  enum: [0, 1]
                id:
                  type: integer
              number:
                  type: string  
              firstName:
                  type: string
              lastName:
                  type: string
              mobile:
                  type: string
              image:
                  type: string
              email:
                  type: string
                  format: email
              birth:
                  type: string
              company:
                  type: string
      "400":
        description: Invalid credentials
      "401":
          description: Unauthorized

